-- Comprehensive Physics-I (BS-PH101) MCQ Upload - 69 Questions
-- This script multiplexes questions across all departments sharing the BS-PH101 code.

-- Optional: Uncomment the line below if you want to clear previous BS-PH101 questions first
-- DELETE FROM public.mock_test_questions WHERE paper_code = 'BS-PH101';

INSERT INTO public.mock_test_questions (department, semester, subject, paper_code, question_text, options, correct_index)
SELECT 
    sb.department, 
    sb.semester, 
    sb.subject, 
    'BS-PH101',
    q.question,
    q.opts,
    q.ans
FROM public.subjects_bundle sb
CROSS JOIN (
    VALUES 
    -- From the latest 69-question set
    ('The relaxation time of a damped oscillator is the time in which amplitude falls to:', ARRAY['A/e', 'A/2', '2A', 'Zero'], 0),
    ('The Q-factor of an oscillator is proportional to:', ARRAY['Damping constant', '1/Damping constant', 'Mass only', 'Amplitude'], 1),
    ('Critical damping occurs when damping is:', ARRAY['Minimum', 'Zero', 'Just sufficient to prevent oscillation', 'Infinite'], 2),
    ('The time period of SHM is:', ARRAY['2π√(m/k)', '2π√(k/m)', '√(m/k)', '2πm/k'], 0),
    ('Maximum acceleration in SHM occurs at:', ARRAY['Mean position', 'Extreme position', 'Half amplitude', 'Anywhere'], 1),
    ('Intensity in interference is proportional to:', ARRAY['A', 'A²', '1/A', '√A'], 1),
    ('Condition for constructive interference is:', ARRAY['Path difference = (2n+1)λ/2', 'Path difference = nλ', 'λ/4', 'Zero always'], 1),
    ('Central maximum in diffraction is:', ARRAY['Narrowest', 'Brightest and widest', 'Dark', 'Absent'], 1),
    ('Resolving power of grating increases with:', ARRAY['Order only', 'Number of slits only', 'Product of order and number of slits', 'Wavelength'], 2),
    ('Brewster’s angle satisfies:', ARRAY['tan i = μ', 'sin i = μ', 'cos i = μ', 'tan r = μ'], 0),
    ('LASER light is:', ARRAY['Incoherent', 'Divergent', 'Monochromatic and coherent', 'Random'], 2),
    ('Spontaneous emission is:', ARRAY['Stimulated by photon', 'Without external influence', 'Forbidden', 'Coherent'], 1),
    ('Stimulated emission produces light that is:', ARRAY['Incoherent', 'Same phase and direction', 'Random phase', 'Different frequency'], 1),
    ('de Broglie wavelength is:', ARRAY['h/mc', 'h/p', 'p/h', 'mc/h'], 1),
    ('de Broglie wavelength decreases when velocity:', ARRAY['Decreases', 'Increases', 'Zero', 'Constant'], 1),
    ('Compton shift is maximum when scattering angle is:', ARRAY['0°', '45°', '90°', '180°'], 3),
    ('Work function is the minimum energy required to:', ARRAY['Excite atom', 'Remove electron', 'Ionize nucleus', 'Break bond'], 1),
    ('Fermi energy depends on:', ARRAY['Temperature only', 'Electron density', 'Pressure only', 'Volume only'], 1),
    ('At 0 K, all states below Fermi level are:', ARRAY['Empty', 'Half filled', 'Completely filled', 'Random'], 2),
    ('Bose-Einstein statistics is applicable to:', ARRAY['Electrons', 'Protons', 'Photons', 'Neutrons'], 2),
    ('Fermi-Dirac statistics is applicable to:', ARRAY['Bosons', 'Fermions', 'Photons', 'Classical particles'], 1),
    ('Stefan-Boltzmann law states power ∝:', ARRAY['T', 'T²', 'T³', 'T⁴'], 3),
    ('Wien’s law states λmax ∝:', ARRAY['T', '1/T', 'T²', 'Constant'], 1),
    ('Rayleigh-Jeans law fails at:', ARRAY['Low frequency', 'High frequency', 'Zero frequency', 'Medium frequency'], 1),
    ('Gradient of a scalar gives:', ARRAY['Scalar', 'Vector', 'Tensor', 'Zero'], 1),
    ('Divergence represents:', ARRAY['Rotation', 'Flux density', 'Curl', 'Gradient'], 1),
    ('If curl F = 0, field is:', ARRAY['Rotational', 'Conservative', 'Divergent', 'Zero'], 1),
    ('Gauss law states ∇·E equals:', ARRAY['ρ/ε₀', '0', 'μ₀J', '−∂B/∂t'], 0),
    ('∇·B equals:', ARRAY['μ₀J', 'ρ/ε₀', '0', '∂E/∂t'], 2),
    ('Ampere-Maxwell law includes:', ARRAY['Conduction current only', 'Displacement current only', 'Both currents', 'No current'], 2),
    ('Electric field inside conductor is:', ARRAY['Maximum', 'Zero', 'Constant', 'Infinite'], 1),
    ('Capacitance unit is:', ARRAY['Henry', 'Farad', 'Tesla', 'Weber'], 1),
    ('Energy stored in capacitor is:', ARRAY['CV²', '½CV²', 'V²/C', 'C/V²'], 1),
    ('Magnetic force on charge is maximum when angle is:', ARRAY['0°', '30°', '90°', '180°'], 2),
    ('Lorentz force is:', ARRAY['qE', 'qvB', 'q(E + v×B)', 'v×B'], 2),
    ('Miller indices are reciprocals of:', ARRAY['Coordinates', 'Intercepts', 'Angles', 'Edges'], 1),
    ('Number of atoms in FCC unit cell is:', ARRAY['2', '4', '6', '8'], 1),
    ('Coordination number in FCC is:', ARRAY['6', '8', '12', '4'], 2),
    ('Bragg’s law is:', ARRAY['nλ = 2d sinθ', 'λ = d sinθ', 'nλ = d cosθ', 'λ = 2d cosθ'], 0),
    ('Relativistic mass increases with:', ARRAY['Decrease in velocity', 'Increase in velocity', 'Zero velocity', 'Constant velocity'], 1),
    ('Time dilation implies moving clock runs:', ARRAY['Faster', 'Slower', 'Same', 'Backward'], 1),
    ('Length contraction occurs along:', ARRAY['Perpendicular direction', 'Direction of motion', 'All directions', 'Random'], 1),
    ('Hamiltonian represents:', ARRAY['Momentum', 'Energy', 'Force', 'Torque'], 1),
    ('If Lagrangian independent of time, energy is:', ARRAY['Not conserved', 'Conserved', 'Zero', 'Infinite'], 1),
    ('Centre of mass depends on:', ARRAY['Shape only', 'Mass distribution', 'Volume only', 'Density only'], 1),
    ('Group velocity is:', ARRAY['dω/dk', 'ω/k', 'k/ω', 'λf'], 0),
    ('Phase velocity is:', ARRAY['dω/dk', 'ω/k', 'k/ω', 'λ/T'], 1),
    ('In non-dispersive medium:', ARRAY['vg > vp', 'vg < vp', 'vg = vp', 'vg = 0'], 2),
    ('Probability density is given by:', ARRAY['ψ', 'ψ²', '|ψ|²', '1/ψ'], 2),
    ('Schrödinger equation is:', ARRAY['Relativistic', 'Non-relativistic wave equation', 'Classical law', 'Statistical law'], 1),
    ('Heisenberg uncertainty principle is:', ARRAY['ΔxΔp ≥ ħ/2', 'ΔxΔp = 0', 'ΔEΔt = 0', 'Δx = Δp'], 0),
    ('Photon energy is:', ARRAY['mc²', 'hf', 'h/p', 'p²/2m'], 1),
    ('Momentum of photon is:', ARRAY['mc', 'h/λ', 'λ/h', 'hf'], 1),
    ('Photoelectric effect supports:', ARRAY['Wave theory', 'Particle nature', 'Sound theory', 'Classical theory'], 1),
    ('Threshold frequency depends on:', ARRAY['Intensity', 'Material', 'Distance', 'Voltage'], 1),
    ('Electric flux unit is:', ARRAY['Volt', 'Nm²/C', 'Tesla', 'Coulomb'], 1),
    ('Gauss theorem relates flux with:', ARRAY['Potential', 'Charge enclosed', 'Current', 'Resistance'], 1),
    ('Magnetic field due to straight conductor varies as:', ARRAY['r', '1/r', 'r²', 'Constant'], 1),
    ('EM waves are:', ARRAY['Longitudinal', 'Transverse', 'Mechanical', 'Stationary'], 1),
    ('Speed of EM wave in vacuum is:', ARRAY['3×10⁶ m/s', '3×10⁸ m/s', '3×10⁵ m/s', '3×10⁷ m/s'], 1),
    ('Poynting vector represents:', ARRAY['Charge density', 'Energy flow', 'Force', 'Voltage'], 1),
    ('Intrinsic semiconductor at 0K behaves as:', ARRAY['Conductor', 'Semiconductor', 'Insulator', 'Superconductor'], 2),
    ('Energy band gap in conductor is:', ARRAY['Large', 'Small', 'Zero', 'Infinite'], 2),
    ('In p-type semiconductor majority carriers are:', ARRAY['Electrons', 'Holes', 'Protons', 'Neutrons'], 1),
    ('In n-type semiconductor majority carriers are:', ARRAY['Holes', 'Electrons', 'Ions', 'Neutrons'], 1),
    ('Drift velocity is proportional to:', ARRAY['Resistance', 'Electric field', 'Charge only', 'Mass'], 1),
    ('Mobility is defined as:', ARRAY['vd/E', 'E/vd', 'I/V', 'V/I'], 0),
    ('Resistivity unit is:', ARRAY['Ω', 'Ωm', 'S/m', 'V/m'], 1),
    ('Kirchhoff’s voltage law is based on conservation of:', ARRAY['Charge', 'Energy', 'Momentum', 'Mass'], 1)
) AS q(question, opts, ans)
WHERE sb.paper_code = 'BS-PH101';
