// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:1003021617321:web:9a017a9e4022dfee7241b8',
        messagingSenderId: '1003021617321',
        projectId: 'makaut-scholar-cb82e',
        authDomain: 'makaut-scholar-cb82e.firebaseapp.com',
        storageBucket: 'makaut-scholar-cb82e.firebasestorage.app',
        measurementId: 'G-MCSNQ00XCW',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
        appId: '1:1003021617321:android:42dd6501ffec831d7241b8',
        messagingSenderId: '1003021617321',
        projectId: 'makaut-scholar-cb82e',
        storageBucket: 'makaut-scholar-cb82e.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:1003021617321:ios:3b43a01400ce7e0b7241b8',
        messagingSenderId: '1003021617321',
        projectId: 'makaut-scholar-cb82e',
        storageBucket: 'makaut-scholar-cb82e.firebasestorage.app',
        iosBundleId: 'com.example.makautScholar',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:1003021617321:ios:3b43a01400ce7e0b7241b8',
        messagingSenderId: '1003021617321',
        projectId: 'makaut-scholar-cb82e',
        storageBucket: 'makaut-scholar-cb82e.firebasestorage.app',
        iosBundleId: 'com.example.makautScholar',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:1003021617321:web:1149c04cbf2ff7fc7241b8',
        messagingSenderId: '1003021617321',
        projectId: 'makaut-scholar-cb82e',
        authDomain: 'makaut-scholar-cb82e.firebaseapp.com',
        storageBucket: 'makaut-scholar-cb82e.firebasestorage.app',
        measurementId: 'G-GC7PY1WKRE',
      );
}
